SumState-Alerting
OpenEMS/odoo-openems pull request #3
Opened 2023-09-14 11:44 UTC by da-Kai

## Description:

Notify specific users of the persistent presence of a negative sumState.

This pull request is linked to the following:
https://github.com/OpenEMS/openems/pull/2260

2024-01-11 16:12 UTC, michaelgrill requested changes

2024-01-11 16:12 UTC, michaelgrill commented on openems/controllers/alerting.py
> +            #template = self.__get_template(msg.edgeId)
remove unnecessary comments

2024-01-11 16:12 UTC, michaelgrill commented on openems/controllers/alerting.py
> +                #role.write({"offline_last_notification": msg.sentAt})
remove unnecessary comments

2024-01-11 16:12 UTC, michaelgrill commented on openems/mail/openems/alerting_sum_state.xml
> +                                    <stong>UNKNOWN </stong>
i think you meant `<strong>`

2024-01-11 16:12 UTC, michaelgrill commented on openems/mail/openems/alerting_sum_state.xml
> +                        <div style="font-family:helvetica;font-size:16px;line-height:1;text-align:left;color:#000000;">If you do no longer wish to receive email notifications, you can disable the fea
you forgot to translate `hier` to `here` at the and with the link

2024-01-11 16:12 UTC, michaelgrill commented on openems/controllers/alerting.py
> +            template = request.env.ref('openems.alerting_sum_state')
wouldnt it make more sense to get this outsite the loop?

2024-01-11 16:12 UTC, michaelgrill commented on openems/controllers/alerting.py
> +        template = request.env.ref("openems.alerting_offline")
do you even need the `device_id` here? If not you could also move the method call outside the loop; also maybe decide on one way to get the template via method or directly with env

2024-01-11 16:12 UTC, michaelgrill commented on openems/models/device.py
> +    @api.depends("user_id")
does it also need to depend on `device_id`?

2024-01-12 12:17 UTC, michaelgrill approved these changes
🙂👍

2024-01-12 12:18 UTC, michaelgrill commented
@sfeilmeier FYI finished with my review

2024-01-12 14:36 UTC, sfeilmeier approved these changes
Ok from my side!

Please do an internal PR as well, because Odoo-OpenEMS-Addon and our internal module are not fully in sync yet, unfortunately.

2024-01-12 14:36 UTC, merged